//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class chart_of_accounts
    {
        public int chart_id { get; set; }
        public string account_name { get; set; }
        public string account_code { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> modified_datetime { get; set; }
        public Nullable<int> modified_by { get; set; }
    }
}
