//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeList
    {
        public int employee_Id { get; set; }
        public string name { get; set; }
        public string fatherName { get; set; }
        public string phoneNum1 { get; set; }
        public string phoneNum2 { get; set; }
        public string phoneNum3 { get; set; }
        public string homePhoneNum { get; set; }
        public string cnicNum { get; set; }
        public string address { get; set; }
        public string referenceName { get; set; }
        public string referencePhoneNum { get; set; }
        public string jobStatus { get; set; }
        public int designation { get; set; }
        public string employeePic1 { get; set; }
        public string employeePic2 { get; set; }
        public string employeeCnicFront { get; set; }
        public string employeeCnicBsck { get; set; }
        public string recruitmentType { get; set; }
        public Nullable<int> weeklySalary { get; set; }
        public Nullable<int> monthlySalary { get; set; }
        public int chart_id { get; set; }
    }
}
