//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class finance_entries
    {
        public int finance_entries_id { get; set; }
        public decimal debit { get; set; }
        public decimal credit { get; set; }
        public string description { get; set; }
        public int finance_main_id { get; set; }
        public string entry_type { get; set; }
        public int chart_id { get; set; }
    }
}
