//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class finance_main
    {
        public int finance_main_id { get; set; }
        public string voucher_type_id { get; set; }
        public string voucher_inv { get; set; }
        public string voucher_date { get; set; }
        public string description { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public string created_datetime { get; set; }
        public string modified_datetime { get; set; }
        public Nullable<int> production_id { get; set; }
    }
}
