//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gate_pass_entries
    {
        public int gate_pass_entries_id { get; set; }
        public Nullable<int> borderSize_id { get; set; }
        public Nullable<int> borderQuality_id { get; set; }
        public string roll_no { get; set; }
        public Nullable<int> pieces { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<int> gate_pass_id { get; set; }
    }
}
