//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gate_pass_main
    {
        public int gate_pass_id { get; set; }
        public string gate_pass_no { get; set; }
        public string party_name { get; set; }
        public string party_cell { get; set; }
        public string party_address { get; set; }
        public Nullable<int> total_rolls { get; set; }
        public Nullable<int> total_pieces { get; set; }
        public Nullable<decimal> total_sharing_weight { get; set; }
        public Nullable<int> color { get; set; }
        public string dying_process { get; set; }
        public Nullable<decimal> total_dying_weight { get; set; }
        public string remarks { get; set; }
        public string driver_name { get; set; }
        public string vehicle_no { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<System.DateTime> modified_datetime { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
    }
}
