//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class grayProductList
    {
        public int grayProduct_id { get; set; }
        public Nullable<int> itemName { get; set; }
        public Nullable<int> itemSize { get; set; }
        public string PerPieceGrayWeightGram { get; set; }
        public string graySizeppWidth { get; set; }
        public string graySizeppLength { get; set; }
        public string LoomNumbPieceInBorder76_ { get; set; }
        public string LoomNumbRatePerBorderWithDraw76 { get; set; }
        public string LoomNumbRatePerBorderWithoutDraw76 { get; set; }
        public string LoomNumbPieceInBorder96 { get; set; }
        public string LoomNumbRatePerBorderWithDraw96 { get; set; }
        public string LoomNumbRatePerBorderWithoutDraw96 { get; set; }
        public string status { get; set; }
    }
}
