//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class grayProductList
    {
        public int grayProduct_id { get; set; }
        public Nullable<int> itemName { get; set; }
        public Nullable<int> itemSize { get; set; }
        public Nullable<decimal> PerPieceGrayWeightGram { get; set; }
        public Nullable<decimal> graySizeppWidth { get; set; }
        public Nullable<decimal> graySizeppLength { get; set; }
        public Nullable<decimal> LoomNumbPieceInBorder76 { get; set; }
        public Nullable<decimal> LoomNumbRatePerBorderWithDraw76 { get; set; }
        public Nullable<decimal> LoomNumbRatePerBorderWithoutDraw76 { get; set; }
        public Nullable<decimal> LoomNumbPieceInBorder96 { get; set; }
        public Nullable<decimal> LoomNumbRatePerBorderWithDraw96 { get; set; }
        public Nullable<decimal> LoomNumbRatePerBorderWithoutDraw96 { get; set; }
        public string status { get; set; }
        public Nullable<decimal> nativingRate76 { get; set; }
        public Nullable<decimal> nativingRate96 { get; set; }
    }
}
