//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoomList
    {
        public int loom_id { get; set; }
        public string loomNumber { get; set; }
        public string loomSize { get; set; }
        public string drawBox { get; set; }
        public string jacquard { get; set; }
        public Nullable<int> weavingUnitId { get; set; }
    }
}
