//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagePermission
    {
        public string PermissionId { get; set; }
        public string RoleId { get; set; }
        public string PageId { get; set; }
        public string EditPermission { get; set; }
        public string viewPermission { get; set; }
        public string DelPermission { get; set; }
        public string AddPermission { get; set; }
    }
}
