//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class production
    {
        public int production_id { get; set; }
        public string roll_no { get; set; }
        public System.DateTime production_date { get; set; }
        public decimal roll_weight { get; set; }
        public int loom_id { get; set; }
        public int borderSize_id { get; set; }
        public int borderQuality_id { get; set; }
        public string programm_no { get; set; }
        public int grayProduct_id { get; set; }
        public Nullable<decimal> pile_to_pile_length { get; set; }
        public decimal pile_to_pile_width { get; set; }
        public decimal cut_piece_size { get; set; }
        public decimal cut_piece_wieght { get; set; }
        public string remarks { get; set; }
        public decimal total_border { get; set; }
        public decimal total_pieces { get; set; }
        public decimal b_grade_pieces { get; set; }
        public decimal a_grade_pieces { get; set; }
        public decimal current_per_piece_a_weight { get; set; }
        public decimal required_length_p_to_p { get; set; }
        public decimal required_width_p_to_p { get; set; }
        public decimal required_per_piece_a_weight { get; set; }
        public System.DateTime cretad_datetime { get; set; }
        public System.DateTime modified_datetime { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
    }
}
