//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_draft
    {
        public int draft_id { get; set; }
        public string draft_name { get; set; }
        public string user_id { get; set; }
        public string page_name { get; set; }
        public string draft_json { get; set; }
    }
}
